source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PXViewController' do
  pod "PXViewController", :path => "../"
  pod 'PXBlockAlertView'
  pod 'SVProgressHUD'
end

target 'Tests' do
  pod "PXViewController", :path => "../"
end
