source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PXViewController', :exclusive => true do
  pod "PXViewController", :path => "../"
  pod 'PXBlockAlertView'
  pod 'SVProgressHUD'
end

target 'Tests', :exclusive => true do
  pod "PXViewController", :path => "../"


end
